TEST_CHANNEL_NAME = "testing-slackbot"
SCRUM_INITIATE_FILE_NAME = "scrum_initiate_message_payload.json"
TYPE_PUBLIC_CHANNEL_ONLY = "public_channel"
TYPE_PRIVATE_CHANNEL_ONLY = "private_channel"
TYPE_BOTH_CHANNEL = "public_channel, private_channel"
TYPE_ALL_CONVERSATIONS = "public_channel, private_channel, mpim, im"
