name: scrum-bot
on: push
  #schedule:
  #  - cron: '* * * * *'

jobs:
  post_scrum_message:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3
      
      - name: create .env file
        run: |
          echo "SLACK_BOT_USER_OAUTH_TOKEN=${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}" > .env
          echo "SCRUM_CHANNEL_NAME=${{ secrets.SCRUM_CHANNEL_NAME }}" >> .env
          echo "SCRUM_TEXT_FILE_PATH=${{ secrets.SCRUM_TEXT_FILE_PATH }}" >> .env
          
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: run main.py
        run: python3 src/main.py
