name:
on:
  schedule:
    - cron: "00 8 * * 0"
  push:
    branches:
      - main

jobs:
  post_meeting_notification:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3

      - name: create .env file
        run: |
          echo "SLACK_APP_MEETING_NOTIFICATION_TOKEN=${{ secrets.SLACK_APP_MEETING_NOTIFICATION_TOKEN }}" > .env
          echo "MEETING_NOFITICATION_CHANNEL_NAME=${{ secrets.MEETING_NOFITICATION_CHANNEL_NAME }}" >> .env

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run main.py
        run: python3 src/meeting_notification/main.py
